export class Routers {
  private constructor() {
  }

  static INDEX = 'INDEX'
  static SEND_REQUEST_PAGE = 'SendRequestPage'
  static TRANSFER_PAGE = 'TransferPage'
  static HISTORY_PAGE = 'HistoryPage'
  static RECEIVE_SETTING_PAGE = 'ReceiveSettingPage'
  static EDITOR_PAGE = 'EditorPage'
  static QUESTION_PAGE = 'QuestionPage'
  static ABOUT_PAGE = 'AboutPage'
  static DEVELOPER_TOOLS = 'DeveloperToolsPage'
}